// Generated by CoffeeScript 1.10.0
(function() {
  var write_res;

  write_res = function(res, code, headers, body) {
    res.writeHead(code, headers);
    if (body) {
      res.write(body);
    }
    res.end(null);
  };

  exports.write_res = write_res;

}).call(this);
