var lrc =
[
		{time: 0.0,    aqours_css_i: 0,  lrc_o: "待ってて愛の歌",                             lrc_t: "等待着爱的歌曲"},
		{time: 5.0,    aqours_css_i: 0,  lrc_o: "Aqours",                                   lrc_t: "Aqours"},
		{time: 9.0,    aqours_css_i: 0,  lrc_o: "作词：畑亜貴",                              lrc_t: "作词：畑亜貴"},
		{time: 12.0,   aqours_css_i: 0,  lrc_o: "作曲、编曲：山口朗彦",                       lrc_t: "作曲、编曲：山口朗彦"},
		{time: 15.0,   aqours_css_i: 0,  lrc_o: "&nbsp;",                                   lrc_t: "&nbsp;"},
		{time: 17.48,  aqours_css_i: 13, lrc_o: "目を閉じて聞いていたよ　くりかえす波の音を",      lrc_t: "闭上双眼我听见了　潮起又潮落的浪花声"},
		{time: 25.5,   aqours_css_i: 13, lrc_o: "今日は静かに流れてく",                        lrc_t: "今天也依旧静静流淌着"},
		{time: 32.14,  aqours_css_i: 0,  lrc_o: "&nbsp;",                                   lrc_t: "&nbsp;"},
		{time: 34.81,  aqours_css_i: 12, lrc_o: "すれ違うひともなくて　ひとりきり歩く道で",          lrc_t: "在不见过往行人的小路上　独自一人漫步着"},
		{time: 42.41,  aqours_css_i: 12, lrc_o: "ラララ…口ずさむ愛のうた",                      lrc_t: "啦啦啦…轻哼着恋爱之歌"},
		{time: 50.0,   aqours_css_i: 0,  lrc_o: "&nbsp;",                                   lrc_t: "&nbsp;"},
		{time: 51.55,  aqours_css_i: 11, lrc_o: "そんな強い想いなんて",                        lrc_t: "尽管还未能理解"},
		{time: 56.11,  aqours_css_i: 11, lrc_o: "まだわからないけどいつかは",                   lrc_t: "这般强大的思念但总有一天"},
		{time: 60.0,   aqours_css_i: 11, lrc_o: "心からの気持ちこめて　歌ってみたいから",         lrc_t: "我会试着饱含着发自内心的心意放声歌唱"},
		{time: 68.47,  aqours_css_i: 0,  lrc_o: "(それはいつかな)",                           lrc_t: "(但究竟会是在何时)"},
		{time: 71.5,	 aqours_css_i: 0,  lrc_o: "待っててくれるかい？　もっとステキになりたいよ",    lrc_t: "你是否会等待着我? 我还想变的更加完美"},
		{time: 80.44,  aqours_css_i: 0,  lrc_o: "恋はまだまだ　謎に満ちた遠くのパッション",        lrc_t: "恋爱对我还为时尚早 它仍只是个充满谜团的遥远激情"},
		{time: 89.08,  aqours_css_i: 0,  lrc_o: "待っててくれるかい？　もっとステキになりたいよ",    lrc_t: "你是否会等待着我? 我还想变的更加完美"},
		{time: 97.83,  aqours_css_i: 0,  lrc_o: "だからまだまだ知りたいな　(いろんなこと知りたい)", lrc_t: "所以还想要知晓更多(想要知晓一切的种种)"},
		{time: 105.89, aqours_css_i: 0,  lrc_o: "あこがれを　(見つめて)　追いかけよう",          lrc_t: "凝神注视着(憧憬)起身追寻吧"},
		{time: 116.29, aqours_css_i: 0,  lrc_o: "&nbsp;",                                   lrc_t: "&nbsp;"},
		{time: 122.07, aqours_css_i: 1,  lrc_o: "砂時計作れるかな　海辺にて思うことは",          lrc_t: "能不能做出个沙漏来?在海边脑中所想的"},
		{time: 130.0,  aqours_css_i: 2,  lrc_o: "いつもとりとめのないこと",                      lrc_t: "总是如此的不得要领"},
		{time: 136.94, aqours_css_i: 0,  lrc_o: "&nbsp;",                                   lrc_t: "&nbsp;"},
		{time: 139.57, aqours_css_i: 10, lrc_o: "少しだけ切ない気分　ひとりきり立ちどまれば",      lrc_t: "夹带些许感伤的情怀 只要独自一人停下脚步"},
		{time: 147.18, aqours_css_i: 0,  lrc_o: "ラララ…泣けてくる愛のうた",                     lrc_t: "啦啦啦...便会潸然泪下的爱恋情歌"},
		{time: 155.90, aqours_css_i: 0,  lrc_o: "誰にきいてみたらわかる？",                     lrc_t: "只要聆听别人倾诉就能感同身受?"},
		{time: 160.86, aqours_css_i: 0,  lrc_o: "きいてわかるものじゃないよね",                  lrc_t: "恋爱从来都不是如此简单明了"},
		{time: 164.92, aqours_css_i: 0,  lrc_o: "胸を焦がす恋のチカラ　思いっきり歌ってみたいけど", lrc_t: "令心中焦躁不安的恋爱力量 虽说想竭尽所能将它给唱出口"},
		{time: 175.34, aqours_css_i: 0,  lrc_o: "(先のことだね)",                             lrc_t: "(现在还不是时候)"},
		{time: 178.4,  aqours_css_i: 0,  lrc_o: "&nbsp;",                                   lrc_t: "&nbsp;"},
		{time: 178.65, aqours_css_i: 0,  lrc_o: "信じてくれるかい？　きっといつかは歌えるって",     lrc_t: "你是否愿意相信我? 有朝一日我定能放声歌唱"},
		{time: 187.36, aqours_css_i: 0,  lrc_o: "恋のあれこれ　想像だけで未来のミッション",        lrc_t: "光是想像恋爱的二三事 就成了我未来的使命"},
		{time: 195.98, aqours_css_i: 0,  lrc_o: "信じてくれるかい？　きっといつかは歌えるって",     lrc_t: "你是否愿意相信我? 有朝一日我定能放声歌唱"},
		{time: 204.7,  aqours_css_i: 0,  lrc_o: "だからあれこれ考えずに　(なりゆきまかせかな)",    lrc_t: "所以无需再多作考虑(就这样顺着心意吧)"},
		{time: 212.78, aqours_css_i: 0,  lrc_o: "そのうちに　(出会いが)　あるのかな",            lrc_t: "在这时(说不定)就会发生美好的邂逅"},
		{time: 223.51, aqours_css_i: 0,  lrc_o: "&nbsp;",                                   lrc_t: "&nbsp;"},
		{time: 241.95, aqours_css_i: 9,  lrc_o: "愛のうたの響きは",                            lrc_t: "恋爱情歌的乐声"},
		{time: 246.17, aqours_css_i: 4,  lrc_o: "優しく悲しいんだね",                           lrc_t: "既温柔又充满着悲伤"},
		{time: 250.75, aqours_css_i: 7,  lrc_o: "なぜかは知らずに",                           lrc_t: "为何明明一知半解"},
		{time: 255.1,  aqours_css_i: 3,  lrc_o: "ねえ胸が痛いよ",                             lrc_t: "内心却隐隐作痛"},
		{time: 259.41, aqours_css_i: 8,  lrc_o: "愛のうたの香りは",                            lrc_t: "恋爱情歌的香气"},
		{time: 263.79, aqours_css_i: 5,  lrc_o: "潮風より青くて",                              lrc_t: "比起海上吹来的风更为青涩"},
		{time: 267.76, aqours_css_i: 6,  lrc_o: "もっと確かめたい香りさ",                        lrc_t: "却是股让我想更进一步弄清楚"},
		{time: 273.77, aqours_css_i: 0,  lrc_o: "(青く切ない香りさ)",                           lrc_t: "(既青涩又哀伤的熏香)"},
		{time: 280.4,  aqours_css_i: 0,  lrc_o: "&nbsp;",                                   lrc_t: "&nbsp;"},
		{time: 281.21, aqours_css_i: 0,  lrc_o: "待っててくれるかい？　もっとステキになりたいよ",    lrc_t: "你是否会等待着我? 我还想变的更加完美"},
		{time: 289.78, aqours_css_i: 0,  lrc_o: "恋はまだまだ　謎に満ちた遠くのパッション",        lrc_t: "恋爱对我还为时尚早 它仍只是个充满谜团的遥远激情"},
		{time: 298.5,  aqours_css_i: 0,  lrc_o: "待っててくれるかい？　もっとステキになりたいよ",    lrc_t: "你是否会等待着我? 我还想变的更加完美"},
		{time: 307.2,  aqours_css_i: 0,  lrc_o: "だからまだまだ知りたいな　(いろんなこと知りたい)", lrc_t: "所以还想要知晓更多(想要知晓一切的种种)"},
		{time: 315.54, aqours_css_i: 0,  lrc_o: "あこがれを　(見つめて追いかけて)",             lrc_t: "凝神注视着(憧憬起身追寻吧)"},
		{time: 320.0,  aqours_css_i: 0,  lrc_o: "ああ口ずさむラブソング…ラララ…",                 lrc_t: "啊啊口中轻声哼著恋爱情歌...啦啦啦..."},
		{time: 340.07, aqours_css_i: 0,  lrc_o: "&nbsp;",                                   lrc_t: "&nbsp;"},
		{time: 345.0,  aqours_css_i: 0,  lrc_o: "Aqours",                                   lrc_t: "Aqours"},
		{time: 361.0,  aqours_css_i: 0,  lrc_o: "Aqours",                                   lrc_t: "Aqours"}
	];

	var aqours_css =
	[
		"jp_font",
		"chika_col jp_font",
		"riko_col jp_font",
		"kanan_col jp_font",
		"daiya_col jp_font",
		"you_col jp_font",
		"yosiko_col jp_font",
		"hanamaru_col jp_font",
		"mari_col jp_font",
		"ruby_col jp_font",
		"chiri_col jp_font",
		"gk_col jp_font",
		"azalea_col jp_font",
		"cyaron_col jp_font",
		"zh-cn_font",
		"chika_col zh-cn_font",
		"riko_col zh-cn_font",
		"kanan_col zh-cn_font",
		"daiya_col zh-cn_font",
		"you_col zh-cn_font",
		"yosiko_col zh-cn_font",
		"hanamaru_col zh-cn_font",
		"mari_col zh-cn_font",
		"ruby_col zh-cn_font",
		"chiri_col zh-cn_font",
		"gk_col zh-cn_font",
		"azalea_col zh-cn_font",
		"cyaron_col zh-cn_font"
	]