// Generated by CoffeeScript 1.10.0
(function() {
  var fmdb, http, my_u, qr_s, start, url;

  http = require("http");

  url = require("url");

  qr_s = require("querystring");

  fmdb = require("formidable");

  my_u = require("./myutils/myutil");

  start = function(route, handle) {
    (http.createServer(function(request, response) {
      var form, get_data;
      if (request.method === 'GET') {
        get_data = qr_s.parse((url.parse(request.url)).query);
        get_data.header_range = request.headers.range;
        route((url.parse(request.url)).pathname, response, get_data);
        return;
      } else {
        form = new fmdb.IncomingForm();
        form.parse(request, function(err_1, fields, files) {
          var post_data;
          if (!err_1) {
            post_data = {
              fields: fields,
              files: files
            };
            route((url.parse(request.url)).pathname, response, post_data);
          } else {
            my_u.write_res(response, 500, {
              "Content-Type": "text/plain"
            }, err_1 + "\n");
          }
        });
      }
    })).listen(5000);
  };

  exports.start = start;

}).call(this);
